.PHONY: all
all:

.PHONY: update
update:
	update-source
	brew update

.PHONY: upgrade
upgrade:
	brew upgrade
	cd $(HOME)/{{ .source }}/helix && cargo install --path helix-term --locked
	make -C $(HOME)/{{ .source }}/gleam install
	hx --grammar fetch
	hx --grammar build
