theme = "muon"

[editor]
auto-pairs = false
bufferline = "always"
gutters = ["spacer"]
scrolloff = 4
cursorline = false
cursorcolumn = false
mouse = true
color-modes = true

[editor.soft-wrap]
enable = true
wrap-indicator = " ～ "

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 0

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "none"

[editor.whitespace.characters]
nbsp = "-"
newline = "╖"
space = "-"
tab = ">"
tabpad = "-"

[editor.lsp]
auto-signature-help = false
# display-messages = true

[editor.statusline]
left = ["mode", "spacer", "file-base-name", "diagnostics", "spinner"]
center = ["primary-selection-length", "spacer", "selections"]
right = ["position-percentage", "spacer",  "position", "spacer"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
I = ["split_selection_on_newline", "insert_at_line_start"]
A = ["split_selection_on_newline", "insert_at_line_end"]
j = ["keep_primary_selection", "move_line_down"]
k = ["keep_primary_selection", "move_line_up"]

[keys.insert]
ret = ["keep_primary_selection", "collapse_selection", "normal_mode"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
ret = ["keep_primary_selection", "collapse_selection", "normal_mode"]

[keys.normal.'\']
A = ":buffer-close-all"
q = ":buffer-close"
O = ":buffer-close-others"
r = ":reload"
R = ":config-reload"
c = ":config-open"
s = ":pipe sort -u"
"[" = ":theme muon"
"]" = ":theme tau"
"." = ":toggle-option file-picker.git-ignore"
