theme = "muon"

[editor]
auto-pairs = false
bufferline = "always"
gutters = ["diff"]
scrolloff = 2
cursorline = false
cursorcolumn = false
mouse = false
color-modes = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 0

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "none"

[editor.whitespace.characters]
nbsp = "-"
newline = "╖"
space = "-"
tab = ">"
tabpad = "-"

[editor.lsp]

[editor.statusline]
left = ["mode", "spacer", "file-name", "diagnostics", "spinner"]
center = ["primary-selection-length", "spacer", "selections"]
right = ["position-percentage", "spacer",  "position", "spacer"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal]
# i = ["insert_mode", "collapse_selection"]
# a = ["append_mode", "collapse_selection"]
C-o = ":config-open"
C-r = ":config-reload"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"\\" = { s = ":pipe sort -u" }

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"ret" = ["collapse_selection", "normal_mode"]

[keys.insert]
"ret" = ["normal_mode"]
