[[language]]
name = "gleam"
auto-format = true

[[grammar]]
name = "gleam"
# formatter = { command = "gleam", args = ["format", "--stdin"] }
source = { git = "https://github.com/gleam-lang/tree-sitter-gleam", rev = "ae79782c00656945db69641378e688cdb78d52c1" }

[[language]]
name = "gren"
scope = "source.gren"
roots = ["gren.json"]
file-types = ["gren"]
comment-token = "--"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "gren", args = ["format", "--stdin"] }
auto-format = false

[[language]]
name = "go"
formatter = { command = "goimports" }

# [[language]]
# name = "elm"
# formatter = { command = "elm-format", args = ["--stdin"] }

