[[language]]
name = "erlang"
auto-format = false

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "heex"
auto-format = true

[[language]]
name = "elixir"
auto-format = true
language-servers = ["elixir-ls"]

[[language]]
name = "go"

  [language.formatter]
  command = "goimports"

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

  [language-server.typescript-language-server]
  config = { format = { "semicolons" = "insert" } }

[[language]]
name = "scheme"
formatter = { command = "raco", args = ["fmt", "-i"] }
auto-format = true
language-servers = [ "steel-language-server" ]

  [language-server.steel-language-server]
  command = "steel-language-server"
  args = []

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }

  [language-server.rust-analyzer.config]
  check.command = "clippy"
  diagnostics.disabled = ["unlinked-file"]
