[[language]]
name = "erlang"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "heex"
auto-format = true

[[language]]
name = "gren"
scope = "source.gren"
roots = ["gren.json"]
file-types = ["gren"]
comment-token = "--"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "gren", args = ["format", "--stdin"] }
auto-format = false

[[language]]
name = "go"
formatter = { command = "goimports" }

[[language]]
name = "elixir"
auto-format = true
language-servers = ["elixir-ls"]

[language-server.typescript-language-server]
config = { format = { "semicolons" = "insert" } }

[language-server.credo]
command = "credo-language-server"
args = ["--stdio=true"]

[language-server.nextls]
command = "nextls"
args = ["--stdio=true"]

[language-server.lexical]
command = "start_lexical.sh"
args = ["--stdio=true"]

[[grammar]]
name = "gleam"
source = { git = "https://github.com/gleam-lang/tree-sitter-gleam", rev = "b2afa4fd6bb41a7bf912b034c653c90af7ae5122" }

