"ui.background" = { fg = "foreground", bg = "background" }
"ui.virtual" = { fg = "slate_gray" }
"ui.cursor.select" = { fg = "background", bg = "color7" }
"ui.cursor.insert" = { fg = "background", bg = "color6" }
"ui.statusline.separator" = { fg = "gray50" }
"ui.statusline.insert" = { fg = "background", bg = "color1" }
"ui.statusline.select" = { fg = "background", bg = "color2" }

"ui.window" = { fg = "gray55", bg = "#b8b5ae" }
"ui.selection" =  { bg = "#cdc0ca" }
# "ui.cursor" = { bg = "#000000" }
"ui.cursorline.primary" = { bg = "#d2cfcd" }
# "ui.cursorline.primary" = { bg = "#d6d3d1" }
"ui.cursorline.secondary" = { bg = "#bdcac8" }
"ui.cursor.primary" = { bg = "#bdb0ba" }
"ui.cursor.match" = { bg = "#b0bab1" }

"ui.menu" = { fg = "foreground", bg = "ui" }
"ui.menu.selected" = { fg = "background", bg = "color2" }
"ui.popup" = { fg = "foreground", bg = "ui2" }
# "ui.popup" = { fg = "foreground", bg = "#cdcac8" }
"ui.help" = { fg = "background", bg = "foreground" }

"ui.bufferline" = { fg = "foreground2", bg = "ui" }
"ui.bufferline.active" = { fg = "foreground", bg = "ui" }

"ui.statusline" = { fg = "foreground", bg = "ui" }
"ui.statusline.inactive" = { fg = "foreground3", bg = "foreground" }

"diff.plus" = { fg = "#008262" }
"diff.minus" = { fg = "color5" }
"diff.delta" = { fg = "#827C00" }

"constant" = { fg = "foreground" }
"constant.numeric" = { fg = "color3" }
"constructor" = { fg = "color6" }
"function" =  { fg ="foreground" }
"label" = { fg = "color1" }
"attribute" = { fg = "color4" }
"namespace" = { fg = "color2", modifiers = [""] }
"operator" = { fg = "slate_gray", modifiers = [""] }
"punctuation" = { fg = "slate_gray" }
"type" = { fg = "color5" }
"variable" = { fg = "foreground" }
"variable.parameter" = { fg = "color6" }
"function.macro" = { fg = "color1" }
"function.builtin" = { fg = "color1" }
# "function.method" = { fg = "color2" }

"tag" = { fg = "color1" }
"comment" = { fg = "#5d6a68", modifiers = [ "" ] }
"keyword" = { fg = "color1", modifiers = [ "" ] }
"string" = { fg = "color3", modifiers = [ ] }
"ui.virtual.indent-guide" = { fg = "#bfb8bd" }
"ui.virtual.whitespace" = { fg = "#bfb8bd" }
"variable.other.member" = { fg = "color4", modifiers = [""] }
"storage.modifier" = { fg = "dark_slate_gray", modifiers = ["bold"] }
"constant.builtin.boolean" = { fg = "color3" }
"constant.builtin" = { fg = "color4", modifiers = [""] }
"string.special.symbol" = { fg = "color6", modifiers = [] }

"diagnostic" = { bg = "#b6d1d5" }
"warning" = { fg = "#a16207" }
"error" = { fg = "#b91c1c" }
"info" = { fg = "slate_gray" }
"hint" = { fg = "slate_gray" }

[palette]
ui = "#bcb5b3"
ui2 = "#aca5a3"
diagnostics = "#bcf4f5"
# foreground0 = "#0b050b"
foreground = "#2b252b"
# foreground1 = "#4b454b"
foreground2 = "#6b656b"
foreground3 = "#aba5ab"
foreground4 = "#b6d0d6"
# background = "#e1dfd9"
background = "#dddad8"
color1 = "#0A5A6C"
color2 = "#904060"
color3 = "#126880"
color4 = "#793B51"
color5 = "#800000"
color6 = "#864062"
color7 = "#95767E"
color8 = "#A96A7D"
# color22 = "#d4c9ce"
dark_slate_gray = "#2f4f4f"
slate_gray = "#708090"
gray0 = "#000000"
gray1 = "#030303"
gray2 = "#050505"
gray3 = "#080808"
gray4 = "#0a0a0a"
gray5 = "#0d0d0d"
gray6 = "#0f0f0f"
gray7 = "#121212"
gray8 = "#141414"
gray9 = "#171717"
gray10 = "#1a1a1a"
gray11 = "#1c1c1c"
gray12 = "#1f1f1f"
gray13 = "#212121"
gray14 = "#242424"
gray15 = "#262626"
gray16 = "#292929"
gray17 = "#2b2b2b"
gray18 = "#2e2e2e"
gray19 = "#303030"
gray20 = "#333333"
gray21 = "#363636"
gray22 = "#383838"
gray23 = "#3b3b3b"
gray24 = "#3d3d3d"
gray25 = "#404040"
gray26 = "#424242"
gray27 = "#454545"
gray28 = "#474747"
gray29 = "#4a4a4a"
gray30 = "#4d4d4d"
gray31 = "#4f4f4f"
gray32 = "#525252"
gray33 = "#545454"
gray34 = "#575757"
gray35 = "#595959"
gray36 = "#5c5c5c"
gray37 = "#5e5e5e"
gray38 = "#616161"
gray39 = "#636363"
gray40 = "#666666"
gray41 = "#696969"
gray42 = "#6b6b6b"
gray43 = "#6e6e6e"
gray44 = "#707070"
gray45 = "#737373"
gray46 = "#757575"
gray47 = "#787878"
gray48 = "#7a7a7a"
gray49 = "#7d7d7d"
gray50 = "#7f7f7f"
gray51 = "#828282"
gray52 = "#858585"
gray53 = "#878787"
gray54 = "#8a8a8a"
gray55 = "#8c8c8c"
gray56 = "#8f8f8f"
gray57 = "#919191"
gray58 = "#949494"
gray59 = "#969696"
gray60 = "#999999"
gray61 = "#9c9c9c"
gray62 = "#9e9e9e"
gray63 = "#a1a1a1"
gray64 = "#a3a3a3"
gray65 = "#a6a6a6"
gray66 = "#a8a8a8"
gray67 = "#ababab"
gray68 = "#adadad"
gray69 = "#b0b0b0"
gray70 = "#b3b3b3"
gray71 = "#b5b5b5"
gray72 = "#b8b8b8"
gray73 = "#bababa"
gray74 = "#bdbdbd"
gray75 = "#bfbfbf"
gray76 = "#c2c2c2"
gray77 = "#c4c4c4"
gray78 = "#c7c7c7"
gray79 = "#c9c9c9"
gray80 = "#cccccc"
gray81 = "#cfcfcf"
gray82 = "#d1d1d1"
gray83 = "#d4d4d4"
gray84 = "#d6d6d6"
gray85 = "#d9d9d9"
gray86 = "#dbdbdb"
gray87 = "#dedede"
gray88 = "#e0e0e0"
gray89 = "#e3e3e3"
gray90 = "#e5e5e5"
gray91 = "#e8e8e8"
gray92 = "#ebebeb"
gray93 = "#ededed"
gray94 = "#f0f0f0"
gray95 = "#f2f2f2"
gray96 = "#f5f5f5"
gray97 = "#f7f7f7"
gray98 = "#fafafa"
gray99 = "#fcfcfc"
gray100 = "#ffffff"
